In [70]:
import numpy as np

In [71]:
alpha_angle=np.array([20, 25, 30, 35])
beta_dict = {20 : np.array([17, 17, 16, 17, 17]), 25 : np.array([22, 23, 22, 22, 23]), 30:np.array([26, 27, 26, 27, 27]), 35:np.array([32, 32, 32, 32, 32])}
U_dict = {20 : np.array([5.4, 5.7, 5.6, 5.8, 5.8]), 25 : np.array([5.8, 6, 6, 6, 5.8]), 30:np.array([5.8, 5.8, 6, 5.8, 5.8]), 35:np.array([6.2, 5.4, 5.6, 5.6, 5.8])}
time_dict = {20 : np.array([136, 130, 123, 126, 131]) * 1e-6, 25 : np.array([128, 113, 121, 124, 128]) * 1e-6, 30:np.array([121, 111, 121, 110, 118]) * 1e-6, 35:np.array([116, 111, 113, 116, 113]) * 1e-6}

l  = 42e-2
d  = 3.8e-2
ro = 7.8e3
g  = 9.8
R = 15e6*90/(90 + 15e6)
C = 10 * 1e-6
m = ro * (4/3) * np.pi * (d/2)**3
U0 = 6.6
Beta = np.sqrt(d) * 2.1e11/(3 * (1 - 0.3**2))

In [72]:
get_h      = lambda alpha : l * (1 - np.cos(np.radians(alpha)))
get_v      = lambda alpha : np.sqrt(2 * g * get_h(alpha))
get_k      = lambda u1, u2, v1, v2 : (u2 - u1) / (v1 - v2)
get_tau2   = lambda U0, U : R * C * np.log(U0/U)
get_tau1   = lambda v0 : 2.943*(5 * m/ (4* Beta)) * v0**(-1/5)
get_S      = lambda K , v: (1 + K) * (m/2) * v
get_P      = lambda x : Beta * x**(3/2)
get_T_lost = lambda u1, v1, u2, v2 : .5 * m * (u1 - v1)**2 + .5 * m(u2 - v2)**2

In [73]:
v1 = get_v(alpha_angle[0])
v2 = 0
u1 = 0
u2 = get_v(beta_dict[alpha_angle[0]])

get_k(u1, u2, v1, v2)


array([0.85120047, 0.85120047, 0.80146595, 0.85120047, 0.85120047])

In [74]:
get_tau1(get_v(alpha_angle[3]))

5.2834055418161825e-11

In [75]:
get_tau2(6.6, 5.8)

0.00011628986059284205

3.

In [76]:
v1 = get_v(alpha_angle)
v2 = np.zeros(len(v1))
u1 = np.zeros(len(v1))
u2 = [get_v(np.mean(angle)) for key, angle in beta_dict.items()]

k = get_k(u1, u2, v1, v2)

print(get_S(k, u2))

[0.1222915  0.16755915 0.19756023 0.24019232]


5.

In [77]:

print(get_tau2( np.full( (len(alpha_angle)), U0), [np.mean(u) for key, u in U_dict.items()]))

[1.38280351e-04 9.78592930e-05 1.10104306e-04 1.28789987e-04]
